### ISSUE TITLE
Installation fails, system requirements stricter than claimed?

### ISSUE THREAD

**Issue by eddelbuettel** [albersonmiranda/fio#124]
Your DESCRIPTION files says rustc (>= 1.67) but I am failing with 1.75 for both rustc and cargo under Ubuntu 24.04L

```
* installing *source* package ‘fio’ ...
** package ‘fio’ successfully unpacked and MD5 sums checked
** using staged installation
Using cargo 1.75.0
Using rustc 1.75.0 (82e1608df 2023-12-21) (built from a source tarball) 
Building for CRAN.
Cleaning previous `src/Makevars`.
Writing `src/Makevars`.
`tools/config.R` has finished.
** libs
using C compiler: ‘gcc (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0’
# unzip vendor.tar.xz if present
if [ -f ./rust/vendor.tar.xz ]; then \
        tar xf rust/vendor.tar.xz && \                                                                               
        mkdir -p /mnt/build/noble/fio/src/fio/src/.cargo && \ 
        cp rust/vendor-config.toml /mnt/build/noble/fio/src/fio/src/.cargo/config.toml; \ 
fi 
export CARGO_HOME=/mnt/build/noble/fio/src/fio/src/.cargo && \
export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/.cargo/bin" && \
RUSTFLAGS=" --print=native-static-libs" cargo build -j 2 --offline --lib --release --manifest-path=./rust/Cargo.toml --target-dir ./rust/target
   Compiling pulp v0.21.4
   Compiling thiserror v2.0.12
error: unsupported output in build script of `pulp v0.21.4`: `cargo::rustc-check-cfg=cfg(libpulp_const)`
Found a `cargo::key=value` build directive which is reserved for future use.
Either change the directive to `cargo:key=value` syntax (note the single `:`) or upgrade your version of Rust.
See https://doc.rust-lang.org/cargo/reference/build-scripts.html#outputs-of-the-build-script for more information about build script outputs.
warning: build failed, waiting for other jobs to finish...
make: *** [Makevars:27: rust/target/release/libfio.a] Error 101
ERROR: compilation failed for package ‘fio’
```

You can fairly easily replicate this in a the rocker/r2u:24.04 container.

**Comment by albersonmiranda** [comment]
Thanks, @eddelbuettel ! In contact with {faer} ecosystem maintainer (which {pulp} is part of), she can no longer support older Rust versions anymore. Even if `faer = { version = '0.19.4' }` is set in `cargo.toml`, it won't compile. I'm bumping {faer} to latest and msrv to 1.84.

**Comment by eddelbuettel** [comment]
Noted, and thanks for the reply.  I look after builds on Ubuntu, they only have 1.75 (in the LTS releases) so that would block the package.  I am unsure what CRAN has but 1.84 may be a little new for them.

**Comment by albersonmiranda** [comment]
@eddelbuettel Lowest Rust version on CRAN runners today is 1.81.0 (as I see in the [{fio} install logs](https://cran.r-project.org/web/checks/check_results_fio.html)). I can make it as low as 1.77, due to {pulp} msrv. Thanks for the heads up! I'm patching ASAP for 1.77.

Is there any chance to add Rust toolchains to r2u runners in the future? Otherwise, I'll have to wait until 2026 LTS

**Comment by eddelbuettel** [comment]
I (currently at least) use what Ubuntu gives me. That currently ends at 1.75 on all LTS versions.
